In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv('/content/loan-test.csv')

In [3]:
df2=pd.read_csv('/content/loan-train.csv')

In [4]:
df=pd.concat([df1,df2])

In [5]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001015,Male,Yes,0,Graduate,No,5720,0.0,110.0,360.0,1.0,Urban,NaN
1,LP001022,Male,Yes,1,Graduate,No,3076,1500.0,126.0,360.0,1.0,Urban,NaN
2,LP001031,Male,Yes,2,Graduate,No,5000,1800.0,208.0,360.0,1.0,Urban,NaN
3,LP001035,Male,Yes,2,Graduate,No,2340,2546.0,100.0,360.0,NaN,Urban,NaN
4,LP001051,Male,No,0,Not Graduate,No,3276,0.0,78.0,360.0,1.0,Urban,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [6]:
df["Gender"]=df["Gender"].fillna(df["Gender"].mode()[0])

In [7]:
df["Married"]=df["Married"].fillna(df["Married"].mode()[0])
df["Dependents"]=df["Dependents"].fillna(df["Dependents"].mode()[0])
df["Self_Employed"]=df["Self_Employed"].fillna(df["Self_Employed"].mode()[0])
df["Loan_Amount_Term"]=df["Loan_Amount_Term"].fillna(df["Loan_Amount_Term"].mean())
df["Credit_History"]=df["Credit_History"].fillna(df["Credit_History"].mean())
df.isnull().sum()

Loan_ID                0
Gender                 0
Married                0
Dependents             0
Education              0
Self_Employed          0
ApplicantIncome        0
CoapplicantIncome      0
LoanAmount            27
Loan_Amount_Term       0
Credit_History         0
Property_Area          0
Loan_Status          367
dtype: int64

In [8]:
df["LoanAmount"]=df["LoanAmount"].fillna(df["LoanAmount"].mean())

In [9]:
df.isnull().sum()

Loan_ID                0
Gender                 0
Married                0
Dependents             0
Education              0
Self_Employed          0
ApplicantIncome        0
CoapplicantIncome      0
LoanAmount             0
Loan_Amount_Term       0
Credit_History         0
Property_Area          0
Loan_Status          367
dtype: int64

In [10]:
df.drop(columns="Loan_ID",inplace=True)

In [11]:
df["Gender"]=df["Gender"].map({"Male":1,"Female":0})

In [12]:
df["Married"]=df["Married"].map({"Yes":1,"No":0})

In [13]:
df['Dependents'] = df['Dependents'].map({'0': 0, '1': 1, '2': 2, '3+': 4})

In [14]:
df["Education"]=df["Education"].map({'Graduate':1, 'Not Graduate':0})
df["Self_Employed"]=df["Self_Employed"].map({"Yes":1,"No":0})

In [15]:
location_mapping = {
    'Urban': 0,
    'Semiurban': 1,
    'Rural': 2
}

df["Property_Area"]= df["Property_Area"].map(location_mapping)

In [16]:
test_df=df[df["Loan_Status"].isna()]

In [17]:
df=df[~df["Loan_Status"].isna()]

In [18]:
df["Loan_Status"]=df["Loan_Status"].map({'Y':1,'N':0})

<ipython-input-18-8ace59d86b50>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Loan_Status"]=df["Loan_Status"].map({'Y':1,'N':0})

In [19]:
df.head(5)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1,0,0,1,0,5849,0.0,142.51153,360.0,1.0,0,1
1,1,1,1,1,0,4583,1508.0,128.00000,360.0,1.0,2,0
2,1,1,0,1,1,3000,0.0,66.00000,360.0,1.0,0,1
3,1,1,0,0,0,2583,2358.0,120.00000,360.0,1.0,0,1
4,1,0,0,1,0,6000,0.0,141.00000,360.0,1.0,0,1

In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



# Assuming 'Class' is the target variable denoting fraud (1) or not fraud (0)
X = df.drop('Loan_Status', axis=1)  # Features
y = df['Loan_Status']  # Target variable

# Splitting the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features by removing the mean and scaling to unit variance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Applying K-Nearest Neighbors (KNN) algorithm
from sklearn.ensemble import RandomForestClassifier


# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creating a Random Forest Regressor
rf = RandomForestClassifier(random_state=42)

# Fitting the model
rf.fit(X_train, y_train)

# Predicting on the test set
y_pred = rf.predict(X_test)




# Additional evaluation metrics
print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))
# Evaluating the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.42      0.55        43
           1       0.75      0.95      0.84        80

    accuracy                           0.76       123
   macro avg       0.79      0.68      0.70       123
weighted avg       0.78      0.76      0.74       123

Confusion Matrix:
[[18 25]
 [ 4 76]]
Accuracy: 0.76

In [21]:
from imblearn.combine import SMOTETomek
import pandas as pd

# Assuming 'X' is your feature set and 'y' is the target variable (Loan_Status)
# Replace 'X' and 'y' with your actual feature set and target variable

# Initialize SMOTETomek
smote_tomek = SMOTETomek(random_state=42)

# Apply SMOTETomek to your data
X_resampled, y_resampled = smote_tomek.fit_resample(X, y)

X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# Standardize features by removing the mean and scaling to unit variance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Creating a Random Forest Regressor
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

# Predictions on the test set
y_pred = rf.predict(X_test)

# Evaluating the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Additional evaluation metrics
print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.81
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.83      0.82        75
           1       0.81      0.80      0.80        69

    accuracy                           0.81       144
   macro avg       0.81      0.81      0.81       144
weighted avg       0.81      0.81      0.81       144

Confusion Matrix:
[[62 13]
 [14 55]]